global:
  configMapName: bigbankprod-configmap
  activeProfile: prod
  configServerURL: configserver:http://configserver:8071/
  discoveryServerURL: "http://spring-cloud-kubernetes-discoveryserver:80/"
  keyCloakURL: http://keycloak.default.svc.cluster.local:80/realms/master/protocol/openid-connect/certs
  openTelemetryJavaAgent: "-javaagent:/otel/opentelemetry-javaagent.jar"
  otelExporterEndPoint: http://tempo-grafana-tempo-distributor:4318
  otelTracesExporter: otlp
  otelExporterOtlpProtocol: http/protobuf
  otelMetricsExporter: none
  otelLogsExporter: none
  kafkaBrokerURL: kafka-controller-0.kafka-controller-headless.default.svc.cluster.local:9092